# This is the Python mapping for the tickers to be imported into app.py


TICKER_DATA = {
    "AAPL": {"name": "Apple", "sector": "Tech and AI"},
    "MSFT": {"name": "Microsoft", "sector": "Tech and AI"},
    "NVDA": {"name": "Nvidia", "sector": "Tech and AI"},
    "GOOGL": {"name": "Alphabet (Google)", "sector": "Tech and AI"},
    "META": {"name": "Meta", "sector": "Tech and AI"},
    "AMZN": {"name": "Amazon", "sector": "Consumer"},
    "AVGO": {"name": "Broadcom", "sector": "Tech and AI"},
    "TSLA": {"name": "Tesla", "sector": "Tech and AI"},
    "AMD": {"name": "AMD", "sector": "Tech and AI"},
    "LMT": {"name": "Lockheed Martin", "sector": "Defence and aerospace"},
    "RTX": {"name": "RTX", "sector": "Defence and aerospace"},
    "AIR.PA": {"name": "Airbus", "sector": "Defence and aerospace"},
    "RR.L": {"name": "Rolls-Royce", "sector": "Defence and aerospace"},
    "XOM": {"name": "ExxonMobil", "sector": "Energy and oil"},
    "SHEL.L": {"name": "Shell", "sector": "Energy and oil"},
    "BP.L": {"name": "BP", "sector": "Energy and oil"},
    "JPM": {"name": "JP Morgan", "sector": "Finance"},
    "HSBA.L": {"name": "HSBC", "sector": "Finance"},   
    "LSEG.L": {"name": "London Stock Exchange Group", "sector": "Finance"},
    "BARC.L": {"name": "Barclays", "sector": "Finance"},
    "LLY": {"name": "Eli Lilly", "sector": "Healthcare and pharma"},
    "UNH": {"name": "UnitedHealth", "sector": "Healthcare and pharma"},
    "AZN.L": {"name": "AstraZeneca", "sector": "Healthcare and pharma"},
    "GSK.L": {"name": "GSK", "sector": "Healthcare and pharma"},
    "RIO.L": {"name": "Rio Tinto", "sector": "Industrial"},
    "AAL.L": {"name": "Anglo American", "sector": "Industrial"},
    "REL.L": {"name": "RELX", "sector": "Industrial"},
    "NG.L": {"name": "National Grid", "sector": "Industrial"},
    "GLD": {"name": "SPDR Gold Shares", "sector": "Metals"},
    "COST": {"name": "Costco", "sector": "Consumer"},
    "PEP": {"name": "PepsiCo", "sector": "Consumer"},
    "ULVR.L": {"name": "Unilever", "sector": "Consumer"},
    "DGE.L": {"name": "Diageo", "sector": "Consumer"},
    "BATS.L": {"name": "British American Tobacco", "sector": "Consumer"},
    "VOD.L": {"name": "Vodafone", "sector": "Telecom"},
    "BTC-USD": {"name": "Bitcoin", "sector": "Crypto"},
    "ETH-USD": {"name": "Ethereum", "sector": "Crypto"},
    "BIL": {"name": "SPDR 1-3 Month T-Bill ETF", "sector": "Low risk bonds (government)"},
    "VGOV.L": {"name": "Vanguard UK Gilt ETF", "sector": "Low risk bonds (government)"}
}
