use [AdventureWorks2019]

/*** 

--create a function to that returns the top three sales generated by a salesperson, 
--as those sales appear in the Sales.SalesOrderHeader table in the AdventureWorks database

--- https://www.red-gate.com/simple-talk/databases/sql-server/t-sql-programming-sql-server/sql-server-apply-basics/
---https://www.mssqltips.com/sqlservertip/1958/sql-server-cross-apply-and-outer-apply/ 

GO
IF OBJECT_ID (N'fn_sales', N'IF') IS NOT NULL
  DROP FUNCTION dbo.fn_sales
GO
CREATE FUNCTION fn_sales (@SalesPersonID int)
RETURNS TABLE
AS
RETURN
(
  SELECT TOP 3 
    SalesPersonID, 
    ROUND(TotalDue, 2) AS SalesAmount
  FROM 
    Sales.SalesOrderHeader
  WHERE 
    SalesPersonID = @SalesPersonID
  ORDER BY 
    TotalDue DESC
)
GO

--- test it out for salesperson id 285
--SELECT SalesAmount FROM fn_sales(285)


***/


--select * from Sales.SalesOrderHeader

select top 3 SalesPersonID, round(totalDue,2) from Sales.SalesOrderHeader
--where SalesPersonID is not null
--order by SalesPersonID, TotalDue
where SalesPersonID = 285
order by TotalDue desc


SELECT 
  sp.FirstName + ' ' + sp.LastName AS FullName,
  fn.SalesAmount
FROM
  Sales.vSalesPerson AS sp
CROSS APPLY
  fn_sales(sp.BusinessEntityID) AS fn
ORDER BY
  sp.LastName, fn.SalesAmount DESC

 -- SELECT  * FROM    Sales.vSalesPerson 


 /*** Using Cross Apply with CTE - first create a function called dbo.fn_products
 IF OBJECT_ID (N'fn_products', N'IF') IS NOT NULL
  DROP FUNCTION dbo.fn_products
GO
CREATE FUNCTION fn_products (@ProductID int)
RETURNS TABLE
AS
RETURN
(
  SELECT
    p.Name AS ProductName,
    pm.Name AS ProductModel
  FROM
    Production.Product AS p
    LEFT OUTER JOIN Production.ProductModel AS pm
      ON p.ProductModelID = pm.ProductModelID
  WHERE
    p.ProductID = @ProductID
)

GO

SELECT ProductName, ProductModel 
FROM fn_products(707)

**/

-- first define CTE ProductSales. CTE then used in main SELECT statement with fn_products function. 
-- Use CROSS APPLY operator in the FROM clause to join the CTE to the function
WITH   ProductSales (ProductID, TotalSales)    AS
  (SELECT  ProductID, SUM(LineTotal)
    FROM Sales.SalesOrderDetail
    GROUP BY ProductID )
SELECT ps.ProductID,   ps.TotalSales,  fn.ProductModel
FROM   ProductSales AS ps
CROSS APPLY  fn_products(ps.ProductID) AS fn
ORDER BY   ps.ProductID

/*** USE OUTER APPLY Operator
IF OBJECT_ID (N'fn_inventory', N'IF') IS NOT NULL
  DROP FUNCTION dbo.fn_inventory
GO
CREATE FUNCTION fn_inventory (@ProductID int)
RETURNS TABLE
AS
RETURN
(
  SELECT
    ProductID,
    LocationID,
    Quantity
  FROM
    Production.ProductInventory
  WHERE
    ProductID = @ProductID
)
GO

SELECT LocationID, Quantity
FROM fn_inventory(915)
**/

SELECT
  p.ProductID,  p.Name,  fn.Quantity
FROM  Production.Product AS p   
CROSS APPLY  fn_inventory(p.ProductID) AS fn  
ORDER BY p.ProductID

SELECT  p.ProductID,  p.Name,  fn.Quantity
FROM  Production.Product AS p  
OUTER APPLY   fn_inventory(p.ProductID) AS fn
ORDER BY p.ProductID


---- More examples
-- https://www.mssqltips.com

DROP TABLE IF EXISTS #LeftTable;
CREATE TABLE #LeftTable
(
    Id INT,
    Name NVARCHAR(10)
)
INSERT INTO #LeftTable
(
    Id,
    Name
)
VALUES
(1, 'Red'), (2, 'Green'), (3, 'Blue'), (4, 'Yellow'), (5, 'Purple');

DROP TABLE IF EXISTS #RightTable;
CREATE TABLE #RightTable
(
    Id INT,
    ReferenceId INT,
    Name NVARCHAR(10)
)
INSERT INTO #RightTable
(
    Id,
    ReferenceId,
    Name
)
VALUES
(1, 1, 'Dog'), (2, 1, 'Cat'), (3, 2, 'Bird'), (4, 4, 'Horse'), (5, 3, 'Bear'), (6, 1, 'Deer');
GO

-- CROSS APPLY
SELECT L.Name,
       R.Name
FROM #LeftTable L
    CROSS APPLY
(SELECT Name FROM #RightTable R WHERE R.ReferenceId = L.Id) R;

-- INNER JOIN
SELECT L.Name,
       R.Name
FROM #LeftTable L
    INNER JOIN #RightTable R
        ON R.ReferenceId = L.Id;

-- OUTER APPLY
SELECT L.Name,
       R.Name
FROM #LeftTable L
    OUTER APPLY
(SELECT Name FROM #RightTable R WHERE R.ReferenceId = L.Id) R;

-- LEFT OUTER JOIN
SELECT L.Name,
       R.Name
FROM #LeftTable L
    LEFT OUTER JOIN #RightTable R
        ON R.ReferenceId = L.Id;

-- CROSS APPLY with a Table Expression
SELECT *
FROM #LeftTable L
    CROSS APPLY
(
    SELECT TOP 2
        R.Name
    FROM #RightTable R
    WHERE R.ReferenceId = L.Id
    ORDER BY R.Id DESC
) R;





-- https://www.mssqltips.com

USE [tempdb];
GO

DROP TABLE IF EXISTS [Employee];
GO

DROP TABLE IF EXISTS [Department];
GO

CREATE TABLE [Department]
(
    [DepartmentID] [INT] NOT NULL PRIMARY KEY,
    [Name] VARCHAR(250) NOT NULL,
);
GO

CREATE TABLE [Employee]
(
    [EmployeeID] [INT] NOT NULL PRIMARY KEY,
    [FirstName] VARCHAR(250) NOT NULL,
    [LastName] VARCHAR(250) NOT NULL,
    [HireDate] DATE NOT NULL,
    [YearlySalary] DECIMAL(16, 2) NOT NULL,
    [DepartmentID] [INT] NOT NULL
        REFERENCES [Department] (DepartmentID),
);
GO

INSERT INTO [Department]
(
    [DepartmentID],
    [Name]
)
VALUES
(1, N'Engineering'),
(2, N'Administration'),
(3, N'Sales'),
(4, N'Marketing'),
(5, N'Finance');
GO

INSERT INTO [Employee]
(
    [EmployeeID],
    [FirstName],
    [LastName],
    [HireDate],
    [YearlySalary],
    [DepartmentID]
)
VALUES
(1, N'Orlando', N'Gee', '01-01-2023', 60000.00, 1),
(2, N'Keith', N'Harris', '01-21-2023', 60000.00, 2),
(3, N'Donna', N'Carreras', '03-01-2021', 82000.00, 3),
(4, N'Janet', N'Gates', '04-01-2022', 90000.00, 3),
(5, N'Bill', N'North', '07-01-2000', 85000.00, 1),
(6, N'Sally', N'Smith', '07-01-2000', 88000.00, 1);
GO

-- https://www.mssqltips.com

-- Query #1
SELECT *
FROM Department D
    CROSS APPLY
   (SELECT * FROM Employee E WHERE E.DepartmentID = D.DepartmentID) A;
GO

-- Query #2
SELECT *
FROM Department D
    INNER JOIN Employee E
        ON D.DepartmentID = E.DepartmentID;
GO